#.bashrc

# exit non-interactive shell now
if [[ $- != *i* ]]; then
  return
fi

. "$HOME/dotfiles/bash/startup_common"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
